// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var app, bodyParser, cookieParser, express, favicon, fs, index, logger, multer, path, scrape, session;

  console.log("di2>>>" + __dirname);

  express = require('express');

  session = require('express-session');

  favicon = require('serve-favicon');

  path = require('path');

  fs = require('fs');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  multer = require('multer');

  index = require('./routes/index.coffee');

  scrape = require('./routes/scrape.coffee');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(favicon(__dirname + '/public/favicon.ico'));

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(session({
    secret: 'session_secret_key',
    resave: false,
    saveUninitialized: true
  }));

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use('/', index);

  app.use('/index', index);

  app.use('/scrape', scrape);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
