// Generated by CoffeeScript 1.10.0
(function() {
  var TARGET_URL, casper;

  casper = require('casper').create();

  TARGET_URL = "http://kujirahand.com";

  casper.start(TARGET_URL, function() {
    return this.echo(casper.getTitle());
  });

  casper.run();

}).call(this);

//# sourceMappingURL=casper.js.map
