// Generated by CoffeeScript 1.10.0
(function() {
  var normalizePort, onError, op, rd, ss;

  normalizePort = function(val) {
    var port;
    port = parseInt(val, 10);
    if (isNaN(port)) {
      return val;
    }
    if (port >= 0) {
      return port;
    }
    return false;
  };

  onError = function(error) {
    var bind;
    if (error.syscall !== 'listen') {
      throw error;
    }
    bind = typeof port === 'string' ? 'Pipe ' + port : 'Port ' + port;
    switch (error.code) {
      case 'EACCES':
        console.error(bind + ' requires elevated privileges');
        return process.exit(1);
      case 'EADDRINUSE':
        console.error(bind + ' is already in use');
        return process.exit(1);
      default:
        throw error;
    }
  };

  ss = function(req) {
    if (req.session) {
      return req.session.user = req.body.username;
    }
  };

  rd = function(res, forward) {
    return res.render('login', {
      title: "Terrada ART FLATS",
      forward: forward
    });
  };

  op = function(res, page, t, n, galid, mode, userjsonfound) {
    if (galid == null) {
      galid = 'gallery1';
    }
    if (mode == null) {
      mode = 'edit';
    }
    if (userjsonfound == null) {
      userjsonfound = false;
    }
    return res.render(page, {
      title: t,
      username: n,
      galleryid: galid,
      gallerymode: mode,
      userjsonfound: userjsonfound
    });
  };

  module.exports = {
    'normalizePort': normalizePort,
    'onError': onError,
    'ss': ss,
    'rd': rd,
    'op': op
  };

}).call(this);

//# sourceMappingURL=funcs.js.map
