// Generated by CoffeeScript 1.10.0
(function() {
  var express, http, router;

  express = require('express');

  http = require('http');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('casper', {
      title: 'Casper / Phantom.js'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=casperjs.js.map
