// Generated by CoffeeScript 1.10.0
(function() {
  var TARGET_URL, casper, express, http, router;

  express = require('express');

  http = require('http');

  router = express.Router();

  casper = require('casper').create();

  TARGET_URL = "http://kujirahand.com";

  router.get('/', function(req, res) {
    casper.start(TARGET_URL, function() {
      return this.echo(casper.getTitle());
    });
    casper.run();
    return res.render('casper', {
      title: 'Casper / Phantom.js'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=casperjs.js.map
