// Generated by CoffeeScript 1.10.0
(function() {
  var aUrl, b, conn, download, express, file, http, ins, out, router, savepath, url;

  express = require('express');

  http = require('http');

  router = express.Router();

  download = require('my/download.coffee').download;

  url = "http://kujirahand.com/";

  savepath = "public/test.html";

  if (typeof java === 'undefined') {
    console.log("Java is not installed.");
  } else {
    console.log("java.version " + java.lang.System.getProperty("java.version"));
  }

  aUrl = new java["new"].URL(url);

  conn = aUrl.openConnection();

  ins = conn.getInputStream();

  file = new java.io.File(savepath);

  out = new java.io.FileOutputStream(file);

  b = null;

  while ((b = ins.read()) !== -1) {
    out.write(b);
  }

  out.close();

  ins.close();

  download(url, savepath, function() {
    return console.log("ok, kenji");
  });

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'TITLE22'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
