// Generated by CoffeeScript 1.10.0
(function() {
  var download, express, http, java, javaLangSystem, router, savepath, url;

  express = require('express');

  http = require('http');

  router = express.Router();

  download = require('my/download.coffee').download;

  java = require('java');

  javaLangSystem = java["import"]('java.lang.System');

  javaLangSystem.out.printlnSyn('Hello World');

  url = "http://kujirahand.com/";

  savepath = "public/test.html";

  download(url, savepath, function() {
    return console.log("ok, kenji");
  });

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'TITLE22'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
