// Generated by CoffeeScript 1.10.0
(function() {
  var URL, client, download, downloadRec, express, fs, http, param, path, request, router, savedir, savepath, url, url2;

  express = require('express');

  http = require('http');

  router = express.Router();

  download = require('../download.coffee').download;

  downloadRec = require('../download.coffee').downloadRec;

  client = require('cheerio-httpcli');

  URL = require('url');

  request = require('request');

  fs = require('fs');

  path = require('path');

  savedir = "./public/img";

  if (!fs.existsSync(savedir)) {
    console.log(savedir);
    fs.mkdirSync(savedir);
  }

  url = "http://kujirahand.com/";

  savepath = "public/test.html";

  download(url, savepath, function() {
    return console.log("ok, kenji");
  });

  url2 = "https://en.wikipedia.org/wiki/Dog";

  param = {};

  client.fetch(url2, param, function(err, $, res) {
    if (err) {
      console.log("Error:", err);
    }
    return $("img").each(function(idx) {
      var fname, src, src2;
      src = $(this).attr('src');
      if (src != null) {
        src2 = URL.resolve(url2, src);
        console.log(src2);
        fname = URL.parse(src2).pathname;
        fname = savedir + "/" + fname.replace(/[^a-zA^Z0-9\.]+/g, '_');
        return request(src2).pipe(fs.createWriteStream(fname));
      }
    });
  });

  router.get('/', function(req, res) {
    var LINK_LEVEL, TARGET_URL, list;
    LINK_LEVEL = 3;
    TARGET_URL = "http://nodejs.jp/nodejs.org_ja/docs/v0.10/api/";
    list = {};
    list = downloadRec(list, TARGET_URL, LINK_LEVEL, TARGET_URL, 0);
    console.log("list");
    console.log(list);
    return res.render('scrape', {
      title: 'SCRAPE'
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=scrape.js.map
